site_name: Spring Guide
docs_dir: source
site_dir: docs
theme:
  name: gitbook
nav:
  - Введение : index.md
  - Архитектура : archicture.md
  - Архитектура. Практика: a1.md
  - ООП : oop.md
  - Spring IoC: ioc.md
  - QA : qa.md
  