site_name: Spring Guide
docs_dir: source
site_dir: docs
markdown_extensions:
  - codehilite
  - pymdownx.details
  - toc:
      permalink: "#"
      baselevel: 1
theme:
  name: material
nav:
  - Введение : index.md
  - Архитектура : archicture.md
  - Архитектура. Практика: a1.md
  - Разработка интерфейсов : interface.md
  - ООП : oop.md
  - Spring IoC: ioc.md
  - QA : qa.md
  